package middleware

import (
	"HiChat/common"
	"fmt"
	"github.com/dgrijalva/jwt-go"
	"github.com/gin-gonic/gin"
	"go.uber.org/zap"
	"net/http"
	"strconv"
	"time"
)

// JwtSecret Define a secret
var JwtSecret = []byte("HelloWorld")

// Claim define a kind of entity which has user status and other data
type Claim struct {
	UserId uint `json:"user_id"`
	jwt.StandardClaims
}

// GenerateToken return a token generated by the user and issuer information
func GenerateToken(userId uint, issuer string) (string, error) {
	// Set effective time of token
	curTime := time.Now()
	expiredTime := curTime.Add(24 * time.Hour)

	// Set token information
	claim := Claim{
		UserId: userId,
		StandardClaims: jwt.StandardClaims{
			ExpiresAt: expiredTime.Unix(),
			Issuer:    issuer,
		},
	}

	// Get string token
	tokenClaim := jwt.NewWithClaims(jwt.SigningMethodHS256, claim)
	token, err := tokenClaim.SignedString(JwtSecret)
	return token, err
}

// Authentication used in middleware to check if token validate
/*
	can also work like:
		func Authentication(ctx *gin.Context){...}
	and use in router:
		r.GET("/path", Authentication, Handler)
	but in Gin Framework we recommend using the following format
*/
func Authentication() gin.HandlerFunc {
	return func(ctx *gin.Context) {
		token := ctx.Query("token")
		id := ctx.Query("userId")

		userId, err := strconv.Atoi(id)
		if err != nil {
			zap.S().Info("Illegal UserId: ", err.Error())
			common.SendErrorResp(ctx.Writer, http.StatusUnauthorized, "Illegal UserId", nil)
			ctx.Abort()
			return
		}

		if token == "" {
			zap.S().Info("Not Login in yet")
			common.SendErrorResp(ctx.Writer, http.StatusUnauthorized, "Please Login in", nil)
			ctx.Abort()
			return
		} else {
			claim, err := ParseToken(token)
			if err != nil {
				zap.S().Info("token invalidity")
				common.SendErrorResp(ctx.Writer, http.StatusUnauthorized, "token invalidity, Please Login in again", nil)
				ctx.Abort()
				return
			} else if claim.ExpiresAt < time.Now().Unix() {
				zap.S().Info("token expired")
				common.SendErrorResp(ctx.Writer, http.StatusUnauthorized, "token expired, Please Login in again", nil)
				ctx.Abort()
				return
			}

			if claim.UserId != uint(userId) {
				zap.S().Info("Illegal Login in")
				common.SendErrorResp(ctx.Writer, http.StatusUnauthorized, "Login Illegal", nil)
				ctx.Abort()
				return
			}

			fmt.Print("Success to Login in")
			ctx.Next()
		}
	}
}

// ParseToken get the claim information from input token
func ParseToken(token string) (*Claim, error) {
	tokenClaim, err := jwt.ParseWithClaims(token, &Claim{}, func(token *jwt.Token) (interface{}, error) {
		return JwtSecret, nil
	})

	if tokenClaim != nil {
		// exchange type: *Token -> *Claim
		if claim, ok := tokenClaim.Claims.(*Claim); ok && tokenClaim.Valid {
			return claim, nil
		}
	}
	return nil, err
}
